"""add product confidence

Revision ID: 9ac7a242ec3a
Revises: 2b2264103823
Create Date: 2026-07-05 23:40:38.621437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac7a242ec3a'
down_revision: Union[str, Sequence[str], None] = '2b2264103823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('confidence', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'confidence')
    # ### end Alembic commands ###
